---
title: "R Notebook"
output: html_notebook
---



```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(readxl)
library(ggplot2)
library(ggpubr)
```

```{r}
folder_path <- "C:\\Users\\Jonas\\OneDrive - Ruprecht-Karls-Universit채t Heidelberg\\Omics"
folder_path <- "B:\\OneDrive\\OneDrive - Ruprecht-Karls-Universit채t Heidelberg\\Omics"
plate_layout_path <- "C:\\Users\\Jonas\\OneDrive - Ruprecht-Karls-Universit채t Heidelberg\\Omics\\plate_layout.csv"
plate_layout_path <- "B:\\OneDrive\\OneDrive - Ruprecht-Karls-Universit채t Heidelberg\\Omics\\plate_layout.csv"
file_list <- list.files(path = folder_path, pattern = "*.xlsx",full.names = TRUE)

data_list <- list()

# Loop through each file and read the data
for (file in file_list) {
  # Read the xlsx file into a dataframe
  temp_data <- read_excel(file)
  
  # Add a column to indicate the source file
  temp_data <- temp_data %>% mutate(source_file = sub(".*?_(.*?)\\..*$", "\\1", basename(file)))
  
  # Append the dataframe to the list
  data_list <- append(data_list, list(temp_data))
}

# Combine all dataframes into one
combined_data <- bind_rows(data_list)

combined_data <- combined_data %>%
  mutate(Well = sub("-.*", "", Filename)) %>%
  mutate(`Prediction (LabelDependencies)` = ifelse(tolower(`Prediction (LabelDependencies)`) == "dead", "Dead", `Prediction (LabelDependencies)`)) %>%
  mutate(`Prediction (LabelDependencies)` = ifelse(tolower(`Prediction (LabelDependencies)`) == "interphase", "Interphase", `Prediction (LabelDependencies)`)) %>%
  mutate(`Prediction (LabelDependencies)` = ifelse(tolower(`Prediction (LabelDependencies)`) == "prometaphase", "Prometaphase", `Prediction (LabelDependencies)`))

plate_layout <- read_delim(plate_layout_path,delim = ";")

combined_data <- left_join(combined_data, plate_layout)
```

```{r}
filtered <- combined_data %>%
  #filter(source_file=='Jonas') %>%
  rename(Prediction = `Prediction (LabelDependencies)`)
  
cell_count <- filtered %>%
  group_by(Condition, `Prediction`,source_file) %>%
  tally()

cell_perc <- cell_count %>%
  group_by(Condition,source_file) %>%
  mutate(percentage = n / sum(n) * 100)
```

```{r}
ggplot(filtered, aes(x=`Prediction (LabelDependencies) (Confidence)`, group=`Prediction`, fill=`Prediction`)) +
  geom_density(adjust=1.5, alpha=.4)+
  facet_wrap(~source_file)
```

```{r}
filtered %>%
  filter(source_file=='Emma') %>%
  ggplot(aes(x = Condition, y = Diameter, fill = `Prediction`)) + 
  geom_col(position = "dodge") +
  theme_classic()
```

```{r}
summary_df <- cell_perc %>%
  group_by(Condition,Prediction) %>%
  summarise(
    mean_value = mean(percentage),
    se = sd(percentage) / sqrt(n())
  )

ggplot(summary_df, aes(x = Condition, y = mean_value, fill = `Prediction`)) + 
  geom_col(position = "dodge") + 
  geom_errorbar(aes(ymin = mean_value - se, ymax = mean_value + se),position = position_dodge(0.9), width = 0.4) + 
  labs(x = "",y = "Percentage", fill = "Phenotype",title = "Pooled data")+
  ylim(0,100)
```

```{r}

```

```{r}
my_comparisons <- list( c("Dead", "Prometaphase"), c("Prometaphase", "Interphase"), c("Dead", "Interphase") )
ggboxplot(filtered, x = "Prediction", y = "Entropy | DIAGONAL | 1 | 40",
          fill = "Prediction", palette = "jco")+ 
  stat_compare_means(comparisons = my_comparisons,method = "t.test") # Add pairwise comparisons p-value
```

# ```{r}
# # Loop over columns 5 to 13
# for (i in 5:13) {
#   # Get the column name
#   column_name <- colnames(filtered)[i]
#   
#   # Create the plot
#   p <- ggplot(filtered, aes(x=column_name, group=`Prediction`, fill=`Prediction`)) +
#     geom_density(adjust=1.5, alpha=.4)
#   
#   # Print the plot
#   print(p)
# }
# 
# ```
```{r}
ggplot(filtered, aes(x=Circularity, group=`Prediction`, fill=`Prediction`)) +
    geom_density(adjust=1.5, alpha=.4)
```


```{r}
for (value in unique(combined_data$source_file)) {
  filtered <- combined_data %>%
    filter(source_file==value)
  
  plot <- ggplot(filtered,aes(x = Condition, fill = `Prediction (LabelDependencies)`)) + 
    geom_bar(position = "dodge") + 
    ggtitle(value)
  ggsave(filename = paste("plot_", value, ".png", sep = ""), plot = plot)
}
```

